services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - ./prisma/orders.db:/app/prisma/orders.db
    environment:
      DATABASE_URL: "file:./prisma/order.db"